### ISSUE TITLE
Splash Requested URL vs Real URL

### ISSUE THREAD

**Issue by civanescu** [scrapy-plugins/scrapy-splash#205] opened 2019-01-21 14:08 UTC
Hi,

I'm trying to obtain in Python the "last" url form a requested url.
On splash site, here is render.json for google.com: {"requestedUrl": "http://www.google.com/", "url": "https://www.google.com/?gws_rd=ssl", "title": "Google", "geometry": [0, 0, 1024, 768]}

I couldn't obtain the same result using the scrapy_splash module.
If I ask for:
            'requested_url': response.data['requestedUrl'],
            'real_url': response.data['url'],
            'splash_url': response.real_url

I only obtain
{"requested_url": "http://www.google.com/", "real_url": "http://www.google.com/", "splash_url": "http://127.0.0.1:8050/render.json"}

Is there a method, parameter to see the last url?

Thank you

**Comment by JavierRuano** [comment] 2019-01-21 15:40
that issue speaks about.
https://github.com/scrapy-plugins/scrapy-splash/issues/152

**Comment by Gallaecio** [comment] 2019-05-09 12:23
@civanescu Could you check if #152 is a duplicate of this issue, and close this issue in that case?

**Closed as completed** 2019-11-21 16:28 UTC
