### ISSUE TITLE
Is it possible to inherit SplashTextResponse from HtmlResponse but not TextResponse

### ISSUE THREAD

**Issue by JosephDeepIntelli** [scrapy-plugins/scrapy-splash#178] opened 2018-06-22 03:54 UTC
In order to naturally use of CrawlSpider, is it possible to change the super class of SplashTextResponse to HtmlResponse from TextResponse? Though HtmlResponse is just a naive wrapper of TextResponse, However, CrawlSpider use the type of response  as a condition for future processing in method ` _requests_to_follow`, it requires an instance of HtmlResponse but not TextResponse.

**Comment by Gallaecio** [comment] 2019-05-09 11:26
May this be a duplicate of #114?

**Closed as completed** 2019-11-21 16:25 UTC
